apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-replica
  labels:
    app: postgres
spec:
  #strategy:
  #  type: Recreate
  serviceName: "postgres"  
  selector:
    matchLabels:
      app: postgres
  template: 
    metadata:
      labels:
        app: postgres
        tier: postgresReplica    
    spec:
      containers:
        - image: emhoppe/mypostgres
          name: dbreplica
          envFrom:
            - configMapRef:
                name: dbconfigreplica
          ports:
            - containerPort: 5432
              name: dbreplica
          volumeMounts:
            - name: dbreplica
              mountPath: /var/lib/postgresql/data
          #command: ["/bin/bash","-c"]
          #args:
            #- ls /opt;
              #cp /opt/postgresql.conf /var/lib/postgresql/data;
              #exit;
      volumes:
        - name: dbreplica
          persistentVolumeClaim:
            claimName: dbreplica-pv-claim
      nodeSelector:
        name: db-pool


