apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: db1
spec:
  version: "13.1"
  replicas: 2
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi