apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskpy
  labels:
    app: connect  
spec:
  selector:
    matchLabels:
      app: connect
  replicas: 1
  template:
    metadata:
      labels:
        app: connect
    spec:
      containers:
      - name: flaskpod
        image: emhoppe/flaskpy
        ports:
          - containerPort: 5000
      nodeSelector:
        name: app-pool           
