Kubectl delete statefulset db-main
Kubectl delete statefulset mynginx
Kubectl delete statefulset flaskpy
kubectl delete pvc dbreplica-claim
kubectl delete pvc dbmain-pv-claim
kubectl delete pv dbreplica-pv
kubectl delete pv dbmain-pv
kubectl delete svc connectsvc
kubectl delete svc nginxlb
