Kubectl delete statefulset db-main
Kubectl delete statefulset db-replica
kubectl delete pvc dbreplica-pv-claim
kubectl delete pvc dbmain-pv-claim
kubectl delete pv dbreplica-pv
kubectl delete pv dbmain-pv
kubectl delete svc postgres
kubectl delete svc postgreslb
kubectl delete configmap dbconfigmain
kubectl delete configmap dbconfigreplica
Kubectl delete deployment mynginx
Kubectl delete deployment flaskpy
kubectl delete svc connectsvc
kubectl delete ingress flasking
kubectl delete cronjob cronback
kubectl delete cronjob crondate
