kind: PersistentVolume
apiVersion: v1
metadata:
  name: dbmain-pv
  labels:
    tier: postgresMain
    type: local
spec:
  storageClassName: dbmainclass
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dbmain-pv-claim
  labels:
    tier: postgresMain
spec:
  storageClassName: dbmainclass
  capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi       