#kind: PersistentVolume
#apiVersion: v1
#metadata:
#   name: pvdb-replica
#   annotations:
#     volume.beta.kubernetes.io/storage-class: dbclass
#spec:
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain  
#   storageClassName: dbclass
#   local:
#     path: 'd:\\kube\volumes\replica'
#   capacity:
#     storage: 2Gi
#   nodeAffinity:
#    required:
#      nodeSelectorTerms:
#      - matchExpressions:
#        - key: name
#          operator: In
#          values:
#          - db-pool
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvcdb-replica
  labels:
    app: postgres
spec:
  storageClassName: dbclass
  capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi                    