kind: PersistentVolume
apiVersion: v1
metadata:
  name: dbreplica-pv
  labels:
    tier: postgresReplica
    type: local
spec:
  storageClassName: dbreplicaclass
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data2"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dbreplica-pv-claim
  labels:
    tier: postgresReplica
spec:
  storageClassName: dbreplicaclass
  capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi             