CREATE USER replicator WITH REPLICATION ENCRYPTED PASSWORD 'replica1';

CREATE TABLE teste
(
 ID serial,
 nome varchar(25)
);

INSERT INTO teste(nome)
VALUES
 ('campo1'),    
 ('campo2'),
 ('campo3');

CREATE ROLE app_ro WITH PASSWORD 'r910di0cjaAAsd1a68'
   NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION VALID UNTIL 'infinity';

GRANT CONNECT ON DATABASE dbmain TO app_ro;
GRANT USAGE ON SCHEMA public TO app_ro;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO app_ro;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO app_ro;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO app_ro;
 
CREATE USER app_rw WITH PASSWORD '78C9jaWsd891xAc123';

